import { Lieu } from "./types";

// Donnees d'exemple. Noms volontairement fictifs.
// Les lieux "a eviter" portent des noms inventes pour rester des exemples.
// horaires / adresse / tel / site : a remplacer par les vraies infos.
// photos / video : laisser vide pour afficher un emplacement, ou pointer vers /public.
export const LIEUX: Lieu[] = [
  // ----------------------- Marrakech -----------------------
  {
    id: "riad-yasmine",
    name: "Riad Yasmine",
    city: "Marrakech",
    country: "Maroc",
    cat: "hotel",
    verdict: "coup de coeur",
    budget: "€€€",
    tags: ["calme", "patio", "instagrammable", "en couple"],
    reasons: [],
    accroche: "Le patio et sa piscine turquoise, aussi beau qu'en vrai.",
    note: "Je l'avais repéré partout sur Instagram, et pour une fois la réalité est à la hauteur. Le patio est minuscule mais la lumière du matin y est parfaite, l'accueil est doux, et le petit-déjeuner sur le toit vaut le réveil tôt. On dort loin du bruit de la médina, c'est rare. Réservez la chambre à l'étage, plus lumineuse.",
    sponsored: true,
    quartier: "Médina",
    reservation: "En direct par e-mail, plusieurs semaines à l'avance",
    horaires: "Réception ouverte 24h/24",
    adresse: "Derb Jdid, Médina, Marrakech",
    tel: "+212 524 00 12 34",
    site: "https://riadyasmine.com",
  },
  {
    id: "table-du-souk",
    name: "Table du Souk",
    city: "Marrakech",
    country: "Maroc",
    cat: "restaurant",
    verdict: "coup de coeur",
    budget: "€€",
    tags: ["rooftop", "terrasse", "local", "entre amis"],
    reasons: [],
    accroche: "Cuisine du marché sur un toit, sans la note salée des touristes.",
    note: "Une adresse tenue par une famille, où l'on mange ce qui était au marché le matin. La terrasse donne sur les toits, le service prend le temps, et l'addition reste honnête pour la qualité. Prenez le tajine du jour, il change selon l'arrivage.",
    sponsored: false,
    quartier: "Kasbah",
    reservation: "Conseillée le soir",
    horaires: "Tous les jours, 12h-15h et 19h-23h",
    adresse: "Rue de la Kasbah, Marrakech",
    tel: "+212 524 00 22 11",
    site: "https://tabledusouk.com",
  },
  {
    id: "hammam-el-ward",
    name: "Hammam El Ward",
    city: "Marrakech",
    country: "Maroc",
    cat: "spa",
    verdict: "coup de coeur",
    budget: "€€",
    tags: ["détente", "traditionnel", "en couple"],
    reasons: [],
    accroche: "Un vrai hammam de quartier, pas une usine à gommage.",
    note: "Rien de tape-à-l'œil, juste un hammam propre, chaud comme il faut, avec un gommage au savon noir qui remet à neuf. On ressort les jambes en coton. Prenez le créneau du matin, c'est plus calme.",
    sponsored: false,
    quartier: "Guéliz",
    reservation: "Par téléphone la veille",
    horaires: "Tous les jours, 9h-20h",
    adresse: "Avenue Mohammed V, Guéliz, Marrakech",
    tel: "+212 524 00 33 22",
    site: "https://hammamelward.com",
  },
  {
    id: "jardins-ombre",
    name: "Jardins d'Ombre",
    city: "Marrakech",
    country: "Maroc",
    cat: "activite",
    verdict: "correct",
    budget: "€",
    tags: ["calme", "en famille"],
    reasons: [],
    accroche: "Une bulle de fraîcheur, bien mais vite visitée.",
    note: "Un joli jardin pour souffler entre deux ruelles, agréable une petite heure. Ce n'est pas inoubliable et ça se fait vite, mais avec des enfants ou en pleine chaleur, ça dépanne très bien.",
    sponsored: false,
    quartier: "Médina",
    horaires: "Tous les jours, 9h30-18h",
    adresse: "Médina, Marrakech",
    tel: "+212 524 00 44 33",
    site: "https://jardinsdombre.com",
  },
  {
    id: "terrasse-panorama",
    name: "Terrasse Panorama",
    city: "Marrakech",
    country: "Maroc",
    cat: "restaurant",
    verdict: "a eviter",
    budget: "€€€",
    tags: ["vue"],
    reasons: ["attrape-touristes", "trop cher pour la qualité", "photos trompeuses"],
    accroche: "",
    note: "La vue est belle, tout le reste déçoit. On paye surtout l'emplacement et la photo de la carte, pas ce qui arrive dans l'assiette. Servi tiède, portions tristes, et une addition qui pique. Montez-y prendre un thé si vous voulez la vue, rien de plus.",
    sponsored: false,
    quartier: "Place centrale",
    horaires: "Tous les jours, 10h-minuit",
    adresse: "Place centrale, Marrakech",
  },

  // ----------------------- Paris -----------------------
  {
    id: "maison-bloom",
    name: "Maison Bloom",
    city: "Paris",
    country: "France",
    cat: "spa",
    verdict: "coup de coeur",
    budget: "€€€",
    tags: ["détente", "cocon", "en couple"],
    reasons: [],
    accroche: "Le spa cocon où l'on oublie qu'on est à Paris.",
    note: "Petit, feutré, sans musique d'ascenseur ni vente forcée de crème à la fin. Le soin visage est vraiment sur mesure, on m'a posé des questions au lieu de dérouler un protocole. On ressort reposée pour de vrai. Le seul défaut, c'est de devoir repartir.",
    sponsored: true,
    quartier: "9e arrondissement",
    reservation: "En ligne, une à deux semaines à l'avance",
    horaires: "Mar-Sam, 10h-20h",
    adresse: "Rue Notre-Dame-de-Lorette, 9e, Paris",
    tel: "+33 1 42 00 00 00",
    site: "https://maisonbloom.fr",
  },
  {
    id: "petit-comptoir",
    name: "Le Petit Comptoir",
    city: "Paris",
    country: "France",
    cat: "restaurant",
    verdict: "coup de coeur",
    budget: "€€",
    tags: ["bistrot", "intime", "en couple"],
    reasons: [],
    accroche: "Le bistrot de quartier qu'on voudrait garder secret.",
    note: "Une ardoise courte qui change tous les jours, ce qui est toujours bon signe. Le patron connaît ses producteurs, la cuisine est franche, et le rapport qualité prix est rare pour Paris. Réservez, il y a huit tables.",
    sponsored: false,
    quartier: "11e arrondissement",
    reservation: "Indispensable",
    horaires: "Mar-Sam, 12h-14h30 et 19h-22h30",
    adresse: "Rue Oberkampf, 11e, Paris",
    tel: "+33 1 43 00 00 00",
    site: "https://lepetitcomptoir.fr",
  },
  {
    id: "atelier-parfum",
    name: "Atelier Parfum",
    city: "Paris",
    country: "France",
    cat: "activite",
    verdict: "coup de coeur",
    budget: "€€",
    tags: ["original", "en couple"],
    reasons: [],
    accroche: "Composer son parfum, une activité qu'on refait avec plaisir.",
    note: "On repart avec un flacon fait maison et surtout un vrai bon moment. La personne qui anime est passionnée, jamais donneuse de leçons. Parfait pour une après-midi à deux quand il pleut.",
    sponsored: false,
    quartier: "Le Marais",
    reservation: "En ligne",
    horaires: "Mer-Dim, sur réservation",
    adresse: "Rue de Turenne, Le Marais, Paris",
    tel: "+33 1 44 00 00 00",
    site: "https://atelierparfum.fr",
  },
  {
    id: "hotel-maubreuil",
    name: "Hôtel Maubreuil",
    city: "Paris",
    country: "France",
    cat: "hotel",
    verdict: "correct",
    budget: "€€€",
    tags: ["central", "en famille"],
    reasons: [],
    accroche: "Bien situé, sans surprise, ni bon ni mauvais.",
    note: "Emplacement imbattable et chambres impeccables, mais tout est un peu lisse. On dort bien, on ne se souvient de rien. À prendre pour la localisation si vous enchaînez les visites, pas pour l'expérience.",
    sponsored: false,
    quartier: "1er arrondissement",
    reservation: "En ligne",
    horaires: "Réception 24h/24",
    adresse: "Rue de Rivoli, 1er, Paris",
    tel: "+33 1 40 00 00 00",
    site: "https://hotelmaubreuil.fr",
  },
  {
    id: "cafe-instagram",
    name: "Café Miroir",
    city: "Paris",
    country: "France",
    cat: "restaurant",
    verdict: "a eviter",
    budget: "€€",
    tags: ["brunch"],
    reasons: ["photos trompeuses", "portions minuscules", "trop cher pour la qualité"],
    accroche: "",
    note: "Tout est pensé pour la photo, rien pour l'assiette. Le brunch qui fait rêver en ligne arrive minuscule et déjà froid, pour un prix qui n'a aucun sens. On fait la queue dehors pour ça, dommage. Il y a dix meilleures adresses à cinq minutes à pied.",
    sponsored: false,
    quartier: "10e arrondissement",
    horaires: "Tous les jours, 9h-17h",
    adresse: "10e arrondissement, Paris",
  },
  {
    id: "croisiere-express",
    name: "Croisière Seine Express",
    city: "Paris",
    country: "France",
    cat: "activite",
    verdict: "a eviter",
    budget: "€€",
    tags: ["vue"],
    reasons: ["attrape-touristes", "trop bruyant"],
    accroche: "",
    note: "Bateau bondé, commentaire hurlé dans trois langues, et on ne voit pas grand-chose depuis le pont. La Seine mérite mieux. Marchez le long des quais au coucher du soleil, c'est gratuit et cent fois plus beau.",
    sponsored: false,
    quartier: "Rive droite",
    horaires: "Départs toutes les heures, 10h-22h",
    adresse: "Embarcadère rive droite, Paris",
  },

  // ----------------------- Lisbonne -----------------------
  {
    id: "tejo-rooftop",
    name: "Tejo Rooftop",
    city: "Lisbonne",
    country: "Portugal",
    cat: "restaurant",
    verdict: "coup de coeur",
    budget: "€€",
    tags: ["rooftop", "vue", "entre amis"],
    reasons: [],
    accroche: "Le coucher de soleil sur le Tage, un verre à la main.",
    note: "Arrivez avant le soleil couchant, prenez un verre et des petiscos, et laissez faire. La cuisine est simple mais bien faite, les prix restent doux, et la vue fait le reste. Un des rares rooftops où l'on paye pour l'assiette autant que pour le panorama.",
    sponsored: false,
    quartier: "Alfama",
    reservation: "Conseillée au coucher du soleil",
    horaires: "Tous les jours, 17h-minuit",
    adresse: "Alfama, Lisbonne",
    tel: "+351 21 000 00 00",
    site: "https://tejorooftop.pt",
  },
  {
    id: "casa-azul",
    name: "Casa Azul",
    city: "Lisbonne",
    country: "Portugal",
    cat: "hotel",
    verdict: "correct",
    budget: "€€",
    tags: ["charme", "central", "en famille"],
    reasons: [],
    accroche: "Du charme et des azulejos, mais des murs fins.",
    note: "Une maison pleine de cachet, bien située pour tout faire à pied. Le bémol, ce sont les murs fins et les rues animées la nuit. Prenez une chambre sur cour et vous serez très bien.",
    sponsored: false,
    quartier: "Baixa",
    reservation: "En ligne",
    horaires: "Réception 8h-22h",
    adresse: "Baixa, Lisbonne",
    tel: "+351 21 000 11 11",
    site: "https://casaazul.pt",
  },
  {
    id: "spa-mares",
    name: "Spa Marés",
    city: "Lisbonne",
    country: "Portugal",
    cat: "spa",
    verdict: "coup de coeur",
    budget: "€€€",
    tags: ["détente", "en couple"],
    reasons: [],
    accroche: "Un parcours d'eau face à l'océan, sans la foule.",
    note: "Le parcours d'eau chaude et froide vaut à lui seul le détour, surtout en fin de journée quand la lumière baisse. Réservez un créneau en semaine pour l'avoir presque pour vous. On en ressort neuve.",
    sponsored: false,
    quartier: "Belém",
    reservation: "En ligne, créneaux limités",
    horaires: "Tous les jours, 10h-21h",
    adresse: "Belém, Lisbonne",
    tel: "+351 21 000 22 22",
    site: "https://spamares.pt",
  },
  {
    id: "tram-vip",
    name: "Tram 28 Tour VIP",
    city: "Lisbonne",
    country: "Portugal",
    cat: "activite",
    verdict: "a eviter",
    budget: "€",
    tags: [],
    reasons: ["attrape-touristes", "trop bruyant"],
    accroche: "",
    note: "On vous vend une expérience exclusive, c'est le tram bondé comme tout le monde, en payant dix fois le prix. Prenez le vrai tram 28 tôt le matin, ou marchez les mêmes ruelles à votre rythme. Vous verrez tout, sans la foule et sans le boniment.",
    sponsored: false,
    quartier: "Graça",
    horaires: "Départs 9h-19h",
    adresse: "Graça, Lisbonne",
  },

  // ----------------------- Bali -----------------------
  {
    id: "ubud-jungle-house",
    name: "Ubud Jungle House",
    city: "Bali",
    country: "Indonésie",
    cat: "hotel",
    verdict: "coup de coeur",
    budget: "€€",
    tags: ["nature", "calme", "piscine", "en couple"],
    reasons: [],
    accroche: "Se réveiller au-dessus de la jungle, la piscine à débordement en prime.",
    note: "On dort dans les arbres, on se réveille avec les oiseaux, et la piscine donne sur la vallée. L'accueil de la famille qui tient les lieux est adorable et sincère. C'est loin de tout, ce qui est exactement l'idée. Prévoyez un scooter ou un chauffeur.",
    sponsored: true,
    quartier: "Ubud",
    reservation: "En direct, quelques semaines à l'avance",
    horaires: "Réception 24h/24",
    adresse: "Ubud, Bali",
    tel: "+62 361 00 00 00",
    site: "https://ubudjunglehouse.com",
  },
  {
    id: "warung-vert",
    name: "Warung Vert",
    city: "Bali",
    country: "Indonésie",
    cat: "restaurant",
    verdict: "coup de coeur",
    budget: "€",
    tags: ["healthy", "local", "entre amis"],
    reasons: [],
    accroche: "Le warung du coin, trois fois rien et tellement bon.",
    note: "Une petite cantine sans chichi où l'on mange local, frais et pour presque rien. Le nasi campur change chaque jour selon ce qui est prêt. C'est le genre d'endroit où l'on revient trois fois dans la semaine.",
    sponsored: false,
    quartier: "Canggu",
    horaires: "Tous les jours, 8h-22h",
    adresse: "Canggu, Bali",
    tel: "+62 361 11 11 11",
    site: "https://warungvert.com",
  },
  {
    id: "beach-club-sunset",
    name: "Beach Club Sunset",
    city: "Bali",
    country: "Indonésie",
    cat: "restaurant",
    verdict: "a eviter",
    budget: "€€€",
    tags: ["plage"],
    reasons: ["trop cher pour la qualité", "trop bruyant", "service décevant"],
    accroche: "",
    note: "Transat à réserver, minimum de conso qui grimpe vite, musique à fond dès l'après-midi et un service qui vous oublie dès que vous avez payé. On paye l'ambiance du feed, pas ce qu'il y a dans le verre. Il y a des plages gratuites et paisibles à dix minutes.",
    sponsored: false,
    quartier: "Seminyak",
    horaires: "Tous les jours, 11h-23h",
    adresse: "Seminyak, Bali",
  },
  {
    id: "rizieres-tegallalang",
    name: "Rizières Tegallalang",
    city: "Bali",
    country: "Indonésie",
    cat: "activite",
    verdict: "correct",
    budget: "€",
    tags: ["nature", "vue", "en famille"],
    reasons: [],
    accroche: "Magnifique tôt le matin, saturée dès 10h.",
    note: "Les rizières en terrasses sont splendides, à condition d'y être au lever du jour. Passé 10h, c'est la foule, les droits d'entrée qui se multiplient à chaque parcelle et la balançoire à selfie. Allez-y très tôt, restez une heure, filez.",
    sponsored: false,
    quartier: "Tegallalang",
    horaires: "Tous les jours, dès 7h",
    adresse: "Tegallalang, Bali",
    tel: "+62 361 22 22 22",
    site: "https://tegallalang-rizieres.com",
  },

  // ----------------------- Bruxelles -----------------------
  {
    id: "the-hotel-brussels",
    name: "The Hotel Brussels",
    city: "Bruxelles",
    country: "Belgique",
    cat: "hotel",
    verdict: "correct",
    budget: "€€€",
    tags: ["central", "vue", "en famille"],
    reasons: [],
    accroche: "La vue sur la ville depuis les étages, le reste est classique.",
    note: "Grand hôtel bien tenu, chambres hautes avec une belle vue sur Bruxelles. C'est efficace et central, mais sans âme particulière. Demandez un étage élevé, c'est ce qui fait la différence ici.",
    sponsored: false,
    quartier: "Avenue Louise",
    reservation: "En ligne",
    horaires: "Réception 24h/24",
    adresse: "Avenue Louise, Bruxelles",
    tel: "+32 2 000 00 00",
    site: "https://thehotelbrussels.be",
  },
  {
    id: "friterie-centrale",
    name: "Friterie Centrale",
    city: "Bruxelles",
    country: "Belgique",
    cat: "restaurant",
    verdict: "a eviter",
    budget: "€",
    tags: [],
    reasons: ["service décevant", "attrape-touristes"],
    accroche: "",
    note: "Sur la place la plus photographiée, donc chère et pressée. Frites molles, accueil expédié, on sent qu'on ne vous reverra pas. Les Bruxellois vont ailleurs, suivez-les. Une bonne friterie de quartier fera dix fois mieux pour moitié prix.",
    sponsored: false,
    quartier: "Centre",
    horaires: "Tous les jours, 11h-23h",
    adresse: "Grand-Place, Bruxelles",
  },
];

export function getLieu(id: string): Lieu | undefined {
  return LIEUX.find((l) => l.id === id);
}
